# Generated by Django 3.2.3 on 2021-05-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sendmail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollnumber',
            name='rollno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
